import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          URL for image below is rewritten to actual URL
        </h1>
        <img src="https://nextjs-redirect-binary.vercel-support.app/mail/image.jpg" />
      </main>
    </div>
  );
}
